### ISSUE TITLE
Limit internet access only to the subnet1

### ISSUE THREAD

**Issue by IsFlwrs** [wizeline-sre/aws-ec2-airflow-terraform#23]
### Context
The subnets used on the VPC are reachable from the internet.

- https://github.com/wizeline-sre/aws-ec2-airflow-terraform/pull/21#discussion_r383661247

### Expectations about this ticket
Limit the exposure of the subnets to the public internet just to the [subnet1](https://github.com/wizeline-sre/aws-ec2-airflow-terraform/blob/master/IaC/main.tf#L108).

### Acceptance criteria
- [ ] Only the subnet1 can be reached from the internet
- [ ] Terraform code is formatted with `terraform fmt`
- [ ] Terraform documentation is up-to-date with `terraform-docs markdown table`
- [ ] Terraform code must follow this [guide](https://www.terraform-best-practices.com/)

### Contributing Guides
- [Commit format](https://github.com/wizeline-sre/aws-ec2-airflow-terraform/blob/master/CONTRIBUTING.md)
- [PR Format](https://medium.com/@jenweber/your-first-open-source-contribution-a-step-by-step-technical-guide-d3aca55cc5a6)
- [Terraform Best Practices](https://www.terraform-best-practices.com/)

**Comment by salvadorcruz10** [comment]
Does not matter if both subnets are public, EC2 instances are located in one of them and the second subnet is just needed to configure RDS (minimal number of subnets), however RDS database is configured as private (CODE in Terraform: publicly_accessible = false). We need to have subnets public to expose the Airflow service, see: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html
